### ISSUE TITLE
https://classic.minecraft.net

### ISSUE THREAD

**Issue by oldmartijntje** [oldmartijntje/oldmartijntje.nl-client#49]
as a user i want to be able to play minecraft in this website so that i can have a fun easteregg

**Comment by Staninna** [comment]
[Reversed engineered classic.minecraft.net](https://github.com/TheSunCat/Minecraft-Classic-Reversed)

I tested it on with `php -S localhost:8111`, and it seems I can't join an already existing server due to lack of a real game server

Screenshot below:
![image](https://github.com/oldmartijntje/oldmartijntje.nl-client/assets/26458805/a459ff5d-87c2-4ab2-9841-b732163e27db)
